<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="generator" content="HTML Tidy for Linux (vers 7 December 2008), see www.w3.org"/>
<meta http-equiv="CONTENT-TYPE" content="text/html; charset=utf-8"/>

<meta name="GENERATOR" content="OpenOffice.org 3.0 (Unix)"/>
<meta name="CREATED" content="20151109;11564100"/>
<meta name="CHANGED" content="20151129;1342700"/>
<meta name="Info_1" content=""/>
<meta name="Info_2" content=""/>
<meta name="Info_3" content=""/>
<meta name="Info_4" content=""/>
<title>Essential Python</title>
<meta content="http://www.w3.org/1999/xhtml; charset=utf-8" http-equiv="Content-Type"/><link href="stylesheet.css" type="text/css" rel="stylesheet"/><style type="text/css">
		@page { margin-bottom: 5.000000pt; margin-top: 5.000000pt; }</style></head>
<body dir="ltr" class="calibre">
<h1 lang="en-GB" class="western3" id="calibre_pb_15"><a id="Exceptions"></a> 17.
Exceptions</h1>
<p lang="en-GB" class="western">Exceptions allow Python to
handle unexpected events when a script is running. If an error
occurs while a script is running Python will generate an exception,
if the exception is not handled then the script will exit, an
exception is an object that represents an error.</p>
<h2 lang="en-GB" class="western4">try - except</h2>
<p lang="en-GB" class="western">If there is part of your script
that might generate an error e.g. opening a file or user input then
it is good practise to protect your code this is done with try and
except statements.</p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6">code to
protect</span></p>
<p lang="en-GB" class="c5"><span class="c6">except
Exception:</span></p>
<p lang="en-GB" class="c5"><span class="c6">if get Exception1 run
this code</span></p>
<p lang="en-GB" class="c5"><span class="c6">else:</span></p>
<p lang="en-GB" class="c5"><span class="c6">if there is no
exception run this code</span></p>
<p lang="en-GB" class="western">Looking at the above syntax of
the <b class="calibre2">try</b> statement you will see there are three parts, the
suite of code in between the <b class="calibre2">try</b> and the <b class="calibre2">except</b>
statement this is the code that will be protected by the <b class="calibre2">try</b>
statement, the code between the <b class="calibre2">exception</b> and the
<b class="calibre2">else</b> this will be run if the defined exception occurs and
finally the <b class="calibre2">else</b> statement which is optional. The code in
the <b class="calibre2">else</b> block will run if the code in the <b class="calibre2">try</b> block
does not cause an exception.</p>
<p lang="en-GB" class="western">More than one type of exception
can be caught by a single <b class="calibre2">try</b> statement by having multiple
<b class="calibre2">except</b> statements.</p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6">code to
protect</span></p>
<p lang="en-GB" class="c5"><span class="c6">except
Exception1:</span></p>
<p lang="en-GB" class="c5"><span class="c6">if get Exception1 run
this code</span></p>
<p lang="en-GB" class="c5"><span class="c6">except
Exception2:</span></p>
<p lang="en-GB" class="c5"><span class="c6">if get Exception2 run
this code</span></p>
<p lang="en-GB" class="c5"><span class="c6">else:</span></p>
<p lang="en-GB" class="c5"><span class="c6">if there is no
exception run this code</span></p>
<p lang="en-GB" class="western">The following example shows how
you can use a <b class="calibre2">try</b> statement to protect you script when
trying to open a file.</p>
<p lang="en-GB" class="c5"><span class="c6"># File:
exceptionsTryExcept.py</span></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c5"><span class="c6"># open a
file</span></p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6">myfile =
open("File.eyr", "r")</span></p>
<p lang="en-GB" class="c5"><span class="c6">except
IOError:</span></p>
<p lang="en-GB" class="c5"><span class="c6">print("Can't open
file")</span></p>
<p lang="en-GB" class="c5"><span class="c6">else:</span></p>
<p lang="en-GB" class="c5"><span class="c6"># read the
file</span></p>
<p lang="en-GB" class="c5"><span class="c6">print(myfile.read())</span></p>
<p lang="en-GB" class="c5"><span class="c6"># close the
file</span></p>
<p lang="en-GB" class="c5"><span class="c6">myfile.close()</span></p>
<p lang="en-GB" class="western">The script catches the IOError
exception and displays an error message if File.err cannot be
opened.</p>
<p lang="en-GB" class="western">If you want to to catch all
exceptions that might occur then <b class="calibre2">except</b> can be used without
any parameters, this is generally not good programming practice as
it will handle any exception with the same code which might not be
valid, so it is best to be explicit about which exceptions are to
be handled.</p>
<p lang="en-GB" class="western">Several exceptions can be
handled with a single <b class="calibre2">except</b> statement as follows.</p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6">code to
protect</span></p>
<p lang="en-GB" class="c5"><span class="c6">except Exception1[,
Exception2[, Exception...]]:</span></p>
<p lang="en-GB" class="c5"><span class="c6">if get any defined
exception run this code</span></p>
<p lang="en-GB" class="c5"><span class="c6">else:</span></p>
<p lang="en-GB" class="c5"><span class="c6">if there is no
exception run this code</span></p>
<h2 lang="en-GB" class="western4">try – finally</h2>
<p lang="en-GB" class="western">Instead of using <b class="calibre2">except</b>
to catch exceptions you can use <b class="calibre2">finally</b>. Code after the
<b class="calibre2">finally</b> statement will also was run even if the code in the
<b class="calibre2">try</b> block causes an exception.</p>
<p lang="en-GB" class="c5"><span class="c6"># File:
exceptionsTryFinally.py</span></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6">myfile =
open('File.eyr', 'r')</span></p>
<p lang="en-GB" class="c5"><span class="c6"># read the
file</span></p>
<p lang="en-GB" class="c5"><span class="c6">print(myfile.read())</span></p>
<p lang="en-GB" class="c5"><span class="c6"># close the
file</span></p>
<p lang="en-GB" class="c5"><span class="c6">myfile.close()</span></p>
<p lang="en-GB" class="c5"><span class="c6">finally:</span></p>
<p lang="en-GB" class="c5"><span class="c6">print('Can't open
file')</span></p>
<p lang="en-GB" class="western">You can not combine
<b class="calibre2">finally</b> with <b class="calibre2">except</b> or <b class="calibre2">else</b> although the
following example shows both types in action.</p>
<p lang="en-GB" class="c5"><span class="c6"># File:
exceptionsTryExceptFinally.py</span></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6">myfile =
open("File.eyr", "r")</span></p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6"># read the
file</span></p>
<p lang="en-GB" class="c5"><span class="c6">print(myfile.read())</span></p>
<p lang="en-GB" class="c5"><span class="c6">finally:</span></p>
<p lang="en-GB" class="c5"><span class="c6"># close the
file</span></p>
<p lang="en-GB" class="c5"><span class="c6">myfile.close()</span></p>
<p lang="en-GB" class="c5"><span class="c6">except
IOError:</span></p>
<p lang="en-GB" class="c5"><span class="c6">print("Can't open
file")</span></p>
<p lang="en-GB" class="western">If an exception is raised once
the file is opened then the file will always closed, the exception
will then be passed to the outer try statement and the error
message will be displayed.</p>
<p lang="en-GB" class="western">If you don't want to handle the
exception and you don't want the script to exit then you can use
pass.</p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6">try
something</span></p>
<p lang="en-GB" class="c5"><span class="c6">except
Exception:</span></p>
<p lang="en-GB" class="c5"><span class="c6">pass</span></p>
<h2 lang="en-GB" class="western4">Exception Arguments</h2>
<p lang="en-GB" class="western">Some exceptions can give more
information by returning a value which can then be used to get more
details about what caused the exception.</p>
<p lang="en-GB" class="western">If your <b class="calibre2">except</b> statement
catches a single exception then by adding a variable after the
exception type you will be able read the extra information. The
value will usually contain information on what caused the exception
and might either contain a single value or multiple values returned
in a tuple. If the value is a tuple then it will usually contain
the error string, error number and the location of the error.</p>
<p lang="en-GB" class="western">The following code creates an
error by trying to convert a non numeric string to an integer. This
causes the exception which then prints out the exception
argument.</p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6">print(int("ry"))</span></p>
<p lang="en-GB" class="c5"><span class="c6">except ValueError as
Args:</span></p>
<p lang="en-GB" class="c5"><span class="c6">print ("Exception
Arg:", Args)</span></p>
<h2 lang="en-GB" class="western4">Raising Exceptions</h2>
<p lang="en-GB" class="western">There may be occasions when you
want your script to raise an exception this can be done by using
the <b class="calibre2">raise</b> statement.</p>
<p lang="en-GB" class="c5"><span class="c6">raise[Exception[,
args[, traceback]]]</span></p>
<p lang="en-GB" class="western">The <b class="calibre2">raise</b> statement
creates an exception the first argument is the name of the
exception, the args parameter is value for the exception, if a
value is not supplied then it will have the value none. The final
argument traceback which is usually not used is the trace back
object used for the exception.</p>
<p lang="en-GB" class="western">Most exceptions that Python
raises are classes with an argument which is an instance of the
class.</p>
<p lang="en-GB" class="c5"><span class="c6"># File:
raiseException.py</span></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c5"><span class="c6"># create an exception
class</span></p>
<p lang="en-GB" class="c5"><span class="c6">class
MyException(Exception):</span></p>
<p lang="en-GB" class="c5"><span class="c6">def __init__(self,
value):</span></p>
<p lang="en-GB" class="c5"><span class="c6">self.parameter =
value</span></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c5"><span class="c6">def
__str__(self):</span></p>
<p lang="en-GB" class="c5"><span class="c6">return
repr(self.parameter)</span></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c5"><span class="c6"># create a function to
use the exception</span></p>
<p lang="en-GB" class="c5"><span class="c6">def
myfunc(value):</span></p>
<p lang="en-GB" class="c5"><span class="c6">if value &lt;
1:</span></p>
<p lang="en-GB" class="c5"><span class="c6">#
print("xx")</span></p>
<p lang="en-GB" class="c5"><span class="c6">raise
MyException(str(value))</span></p>
<p lang="en-GB" class="c5"><span class="c6">print("Ok")</span></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c7"> <br class="calibre1"/></p>
<p lang="en-GB" class="c5"><span class="c6"># test the
exception</span></p>
<p lang="en-GB" class="c5"><span class="c6">try:</span></p>
<p lang="en-GB" class="c5"><span class="c6"># this should be
ok</span></p>
<p lang="en-GB" class="c5"><span class="c6">myfunc(3)</span></p>
<p lang="en-GB" class="c5"><span class="c6"># this should
fail</span></p>
<p lang="en-GB" class="c5"><span class="c6">myfunc(0)</span></p>
<p lang="en-GB" class="c5"><span class="c6">except MyException as
instance:</span></p>
<p lang="en-GB" class="c5"><span class="c6">print("Invalid Value:
" + instance.parameter)</span></p>
<p lang="en-GB" class="western"><br class="calibre1"/>
<br class="calibre1"/></p>
<p lang="en-GB" class="western"><br class="calibre1"/>
<br class="calibre1"/></p>
<p lang="en-GB" class="western"><br class="calibre1"/>
<br class="calibre1"/></p>
<p lang="en-GB" class="western"><br class="calibre1"/>
<br class="calibre1"/></p>
</body>
</html>
